all:
	make -C host
	make -C prime
	make -C aes
	make -C mem
	make -C crypt
	make -C caller
	make -C server
clean:
	make -C host clean
	make -C prime clean
	make -C aes clean
	make -C mem clean
	make -C crypt clean
	make -C caller clean
	make -C server clean
