all:
	make -C host
	make -C prime
	make -C aes
	make -C mem
	make -C crypt
	make -C deadloop
	make -C count
	make -C gm_test_enclaves
	make -C seal_data

clean:
	make -C host clean
	make -C prime clean
	make -C aes clean
	make -C mem clean
	make -C crypt clean
	make -C deadloop clean
	make -C count clean
	make -C gm_test_enclaves clean
	make -C seal_data clean
